#!/usr/bin/env bash

path="$1"
root="$(git rev-parse --show-toplevel)"

if [ -z "$path" ]; then
  git ls-files -v | grep ^S | sed 's/^S //'
  exit 0;
fi;

if [ ! -d .git/overlook ]; then
	mkdir "$root/.git/overlook"
fi;
record="$root/.git/overlook/$(echo $path | sed 's/\./___/g' | sed 's/\//____/g')"
touch "$record"
git update-index --skip-worktree "$path"
